#!/bin/bash

echo "" > /var/log/auth.log
echo "" > /var/log/lastlog
echo "" > /var/log/alternatives.log
echo "" > /var/log/alternatives.log.1
echo "" > /var/log/btmp
echo "" > /var/log/btmp.1
echo "" > /var/log/dmesg
echo "" > /var/log/dpkg.log
echo "" > /var/log/dpkg.log.1
echo "" > /var/log/fail2ban.log
echo "" > /var/log/faillog
echo "" > /var/log/fontconfig.log
echo "" > /var/log/syslog
echo "" > /var/log/syslog.1
echo "" > /var/log/wtmp
echo "" > /var/log/apache2/access.log
echo "" > /var/log/apache2/error.log
echo "" > /var/log/apache2/error.log.1
echo "" > /var/log/apache2/other_vhosts_access.log
echo "" > /var/log/apt/history.log
echo "" > /var/log/apt/term.log
echo "" > /var/log/dbconfig-common/dbc.log
echo "" > /var/log/dbconfig-common/dbc.log.1
echo "" > /var/log/exim4/mainlog
echo "" > /var/log/exim4/mainlog.1
echo "" > /var/log/mysql/error.log
echo "" > /root/.bash_history
